spring.application.name=issuetracker

JWT_SECRET_BASE=yl0rw5jDdTKgaUYB86cw/9xdzefS5to95U3tDnolFmg+

spring.datasource.url=jdbc:mysql://localhost:3306/issuetracker
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update